
sudo: true

install: 
- ./install-dependencies.sh all

before_script:
- test -z "$PREFIX" || export PATH=$PATH:$PREFIX/bin

script:
- echo ENV=$ENV PREFIX=$PREFIX SRC_PREFIX=$SRC_PREFIX
- ./tools/ci/build.sh

env:
  global:
  - username=travis
  - PATH=$PATH:$HOME/bin:$HOME/usr/bin:$HOME/.local/bin/
  - Build_Deps_Default_Paths=1
  matrix:
  - ENV=production sudo=sudo
  - ENV=user-dev PREFIX=$HOME/.local
  - ENV=testing
  - ENV=

branches:
  only:
  - master
  - test
  - '/^[0-9]*\.[0-9]*\.[0-9]*/'

notifications:
  email:
    on_success: never

deploy:
  provider: releases
  api_key: $GH_ACCESS_TOKEN
  file: git-versioning-$TRAVIS_TAG.tar
  on:
    repo: dotmpe/git-versioning
    tags: true
    condition: $ENV = production

