
install: 
- test -z "$PREFIX" && ( export sudo=sudo ./install-dependencies.sh ) || ( PREFIX=$HOME/.local SRC_PREFIX=$HOME/build ./install-dependencies.sh )
- chown -R $username /home/$username/.local

before_script:
- test -z "$PREFIX" || export PATH=$PATH:$PREFIX/bin

script:
- case "$ENV" in
     production ) ./configure.sh /usr/local && sudo ENV=$ENV ./install.sh && make test ;;
     test* | dev* ) ./configure.sh && make test ;;
     * ) ( test -n "$PREFIX" && ( ./configure.sh $PREFIX && ENV=$ENV ./install.sh ) || printf "" ) && make test ;;
  esac

branches:
  only:
  - test
  - '/^[0-9]*\.[0-9]*\.[0-9]*/'

env:
  global:
  - username=travis
  matrix:
  - ENV=production
  - ENV=user-dev PREFIX=$HOME/.local
  - ENV=testing
  - ENV=

deploy:
  provider: releases
  api_key:
    secure: cN2/NBh4TRW9vritc/KopfZksj/oarMC1KV+N4c436usQlcf4uxbanuN26FcO49fQ/2sxT/IFIasvJ0bR6CnALWzsB4Of7FBqCf85m81M/3mTiPRd7yARQdzQHB5p+f+7fTRsdLz3XkaP4Ww1ARYtckDUHnFXJOF9vC2DX/2rL0=
  file: git-versioning-$TRAVIS_TAG.tar
  on:
    repo: dotmpe/git-versioning
    tags: true
    condition: $ENV = production

