# Id: git-versioning/0.1.3 package.yaml
# Start

- type: application/x-project-mpe
  main: git-versioning
  id: git-versioning
  version: 0.1.3 # git-versioning
  environments: [ 'development' ]

  pd-meta:
    #check: ":make:git-pre-commit"
    check: ":vchk :bats-specs :bats:test/git-versioning-spec.bats"
    test: ":vchk :bats-specs :bats"
    git-hooks:
      pre-commit: ./tools/git-hooks/pre-commit.sh
    init: "./install-dependencies.sh git"

# git-versioning main: git-versioning

# End
