# git-versioning main: git-versioning

# Id: git-versioning/0.0.19 package.yaml
# Start

- type: application/x-project-mpe
  id: git-versioning
  version: 0.0.19 # git-versioning
  environments: [ 'development' ]

# End
# Id: git-versioning/0.0.19 package.yaml

