# git-versioning main: git-versioning

# Id: git-versioning/0.0.27-test package.yaml
# Start

- type: application/x-project-mpe
  id: git-versioning
  version: 0.0.27-test # git-versioning
  environments: [ 'development' ]

# End
# Id: git-versioning/0.0.27-test package.yaml

