main: git-versioning

# Id: git-versioning/0.0.16-dev-master+20150504-0239 package.yaml
# Start

- type: application/x-project-mpe
  id: git-versioning
  version: 0.0.16-dev-master+20150504-0239 # git-versioning
  environments: [ 'development' ]

# End
# Id: git-versioning/0.0.16-dev-master+20150504-0239 package.yaml







