 
# Id: git-versioning/0.0.7 package.yaml
# Start

- type: application/x-project-mpe
  id: git-versioning
  version: 0.0.7
  environments: [ 'development' ]

# End
# Id: git-versioning/0.0.7 package.yaml







